# In NumPy dimensions are called axes.

In [7]:
import numpy as np
A = [[ 1, 0, 0],[ 0, 1, 2]]
np.ndim(A)

2

In [10]:
np.ndim(A)

2

In [8]:
np.shape(A)

(2, 3)

In [11]:
A

[[1, 0, 0], [0, 1, 2]]

In [12]:
np.size(A)

6

In [13]:
np.dtype(A)

TypeError: data type not understood

In [14]:
np.itemsize(A)

AttributeError: module 'numpy' has no attribute 'itemsize'

In [15]:
import numpy as np

In [17]:
a = np.arange(15)

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
a = np.arange(15).reshape(3, 5)

In [24]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
a.dtype

dtype('int32')

In [28]:
a.size

15

In [29]:
a.shape

(3, 5)

In [30]:
a.ndim

2

In [31]:
type(a)

numpy.ndarray

In [32]:
a.itemsize

4

In [33]:
a.data

In [34]:
b = np.array([[1,2,3],[2,3,4]])

In [35]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [37]:
b.ndim

2

In [38]:
b.shape

(2, 3)

In [39]:
b.size

6

In [40]:
b.data

In [41]:
b.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [42]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [43]:
b.reshape(6)

array([1, 2, 3, 2, 3, 4])

In [45]:
b.dtype

dtype('int32')

In [46]:
c = np.array([1,2.3,4])

In [47]:
c.dtype

dtype('float64')

In [49]:

a = np.array([1,2.2,5,6,8.7], dtype=int)

In [51]:
a = np.array([1,2.2,5,6,8.7], dtype=int)
a

array([1, 2, 5, 6, 8])

In [53]:
b = np.zeros((4,5))

In [54]:
b.dtype

dtype('float64')

In [55]:
b.reshape(2,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
c = np.ones((3,4))

In [58]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
a = np.empty((3,4))

In [61]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
arr = np.array([[1,2,3], [2,3,4], [2,4,6]])

In [66]:
np.empty()

TypeError: empty() missing required argument 'shape' (pos 1)

In [68]:
np.empty((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [2, 4, 6]])

In [70]:
arr.dtype

dtype('int32')

In [71]:
arr.size

9